import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Sparkles, Wallet, Mail, Calendar, Shield, BarChart3 } from "lucide-react";

export default function Landing() {
  const features = [
    {
      icon: Sparkles,
      title: "AI-Powered Insights",
      description: "Daily briefings generated by advanced AI analyzing your portfolio and lifestyle"
    },
    {
      icon: Wallet,
      title: "Wealth Management",
      description: "Track assets across stocks, crypto, bonds, and real estate in one dashboard"
    },
    {
      icon: Mail,
      title: "Smart Email Automation",
      description: "AI categorizes and drafts replies for your financial and personal emails"
    },
    {
      icon: Calendar,
      title: "Optimized Routines",
      description: "Build billionaire-level daily schedules with proven success patterns"
    },
    {
      icon: BarChart3,
      title: "Portfolio Analytics",
      description: "Real-time tracking with anomaly detection and risk assessment"
    },
    {
      icon: Shield,
      title: "Enterprise Security",
      description: "Bank-level encryption with multi-factor authentication"
    },
  ];

  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-6 py-12">
        <div className="text-center mb-16">
          <h1 className="text-5xl font-bold tracking-tight mb-6">
            Your AI-Powered Life Automation Platform
          </h1>
          <p className="text-xl text-muted-foreground mb-8 max-w-2xl mx-auto">
            Automate wealth management, email handling, and daily routines with cutting-edge AI. 
            Live the billionaire lifestyle with minimal effort.
          </p>
          <Button size="lg" onClick={() => window.location.href = '/api/login'} data-testid="button-get-started">
            Get Started
          </Button>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-16">
          {features.map((feature, index) => (
            <Card key={index} className="p-6" data-testid={`feature-${index}`}>
              <div className="flex items-start gap-4">
                <div className="p-3 rounded-lg bg-primary/10">
                  <feature.icon className="h-6 w-6 text-primary" />
                </div>
                <div>
                  <h3 className="font-semibold mb-2">{feature.title}</h3>
                  <p className="text-sm text-muted-foreground">{feature.description}</p>
                </div>
              </div>
            </Card>
          ))}
        </div>

        <Card className="p-12 bg-gradient-to-br from-primary/5 to-primary/10 border-primary/20">
          <div className="text-center">
            <h2 className="text-3xl font-bold mb-4">Ready to Automate Your Life?</h2>
            <p className="text-muted-foreground mb-8 max-w-xl mx-auto">
              Join thousands of users who've automated their financial and personal management
            </p>
            <Button size="lg" onClick={() => window.location.href = '/api/login'} data-testid="button-sign-in">
              Sign In with Replit
            </Button>
          </div>
        </Card>
      </div>
    </div>
  );
}
