import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Sparkles, Wallet, Mail, Calendar, Shield, BarChart3, ChevronDown, Lock, CheckCircle } from "lucide-react";

export default function Landing() {
  const features = [
    {
      icon: Sparkles,
      title: "AI-Powered Insights",
      description: "Daily briefings generated by advanced AI analyzing your portfolio and lifestyle"
    },
    {
      icon: Wallet,
      title: "Wealth Management",
      description: "Track assets across stocks, crypto, bonds, and real estate in one dashboard"
    },
    {
      icon: Mail,
      title: "Smart Email Automation",
      description: "AI categorizes and drafts replies for your financial and personal emails"
    },
    {
      icon: Calendar,
      title: "Optimized Routines",
      description: "Build billionaire-level daily schedules with proven success patterns"
    },
    {
      icon: BarChart3,
      title: "Portfolio Analytics",
      description: "Real-time tracking with anomaly detection and risk assessment"
    },
    {
      icon: Shield,
      title: "Secure Access",
      description: "Protected authentication with Replit's secure identity platform"
    },
  ];

  const securityFeatures = [
    {
      icon: Lock,
      title: "Secure Authentication",
      description: "Industry-standard OAuth authentication through Replit's trusted platform"
    },
    {
      icon: Shield,
      title: "Protected Sessions",
      description: "Your sessions are managed securely with automatic timeout protection"
    },
    {
      icon: CheckCircle,
      title: "Privacy Focused",
      description: "Your financial data remains private and accessible only to you"
    },
  ];

  return (
    <div className="min-h-screen bg-background">
      {/* Hero Section - Simplified with minimal overlays */}
      <div className="relative min-h-screen flex items-center justify-center overflow-hidden bg-gradient-to-br from-[rgb(10,12,20)] via-[rgb(20,25,35)] to-[rgb(10,12,20)]">
        {/* Single subtle animated gradient - no stacking */}
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,rgba(108,31,255,0.15)_0%,rgba(255,196,61,0.08)_50%,transparent_100%)] animate-pulse-slow pointer-events-none" />

        {/* Hero Content */}
        <div className="relative z-20 text-center px-6 max-w-5xl mx-auto">
          <h1 className="text-3xl sm:text-5xl md:text-6xl font-bold tracking-tight mb-6 bg-gradient-to-br from-primary via-primary/90 to-accent bg-clip-text text-transparent">
            WealthForge
          </h1>
          <p className="text-lg sm:text-xl md:text-2xl font-semibold mb-4 text-foreground/90">
            Elite Life Automation
          </p>
          <p className="text-sm sm:text-base text-muted-foreground mb-12 max-w-3xl mx-auto leading-relaxed">
            Command your wealth, time, and communications with the sophistication of a private office—powered by cutting-edge AI
          </p>
          
          {/* Security Badge */}
          <div className="flex items-center justify-center gap-2 mb-10">
            <Shield className="h-5 w-5 text-primary" />
            <span className="text-sm text-muted-foreground">
              Secured with industry-standard authentication
            </span>
          </div>

          {/* Primary CTA - High Contrast, No Overlays */}
          <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
            <Button 
              asChild
              size="lg" 
              className="text-lg px-12 py-6 h-auto rounded-lg bg-primary hover:bg-primary/90 text-primary-foreground shadow-lg shadow-primary/20 transition-all duration-300 relative z-30"
              data-testid="button-login"
            >
              <a href="/api/login">
                <Lock className="mr-2 h-6 w-6" />
                Secure Sign In
              </a>
            </Button>
            <Button 
              asChild
              size="lg" 
              variant="outline"
              className="text-lg px-12 py-6 h-auto rounded-lg relative z-30"
              data-testid="button-learn-more"
            >
              <a href="#features">
                Explore Features
              </a>
            </Button>
          </div>
          
          {/* Scroll Indicator */}
          <div className="mt-20 animate-bounce">
            <ChevronDown className="h-8 w-8 text-primary/60 mx-auto" />
          </div>
        </div>
      </div>

      {/* Features Section - Clean Design */}
      <div id="features" className="container mx-auto px-6 py-20">
        <div className="text-center mb-16">
          <h2 className="text-2xl sm:text-3xl md:text-4xl font-bold tracking-tight mb-4">
            Executive-Level <span className="text-primary">Automation</span>
          </h2>
          <p className="text-base sm:text-lg text-muted-foreground max-w-2xl mx-auto">
            Experience the precision and efficiency reserved for the world's elite
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-20">
          {features.map((feature, index) => (
            <Card 
              key={index} 
              className="p-8 hover-elevate transition-all duration-300" 
              data-testid={`feature-${index}`}
            >
              <div className="flex flex-col gap-4">
                <div className="p-3 rounded-lg bg-primary/10 w-fit">
                  <feature.icon className="h-8 w-8 text-primary" />
                </div>
                <div>
                  <h3 className="text-lg font-semibold mb-2">{feature.title}</h3>
                  <p className="text-sm text-muted-foreground leading-relaxed">{feature.description}</p>
                </div>
              </div>
            </Card>
          ))}
        </div>

        {/* Security Section */}
        <div className="mb-20">
          <div className="text-center mb-12">
            <h2 className="text-2xl sm:text-3xl font-bold tracking-tight mb-4">
              <span className="text-primary">Secure</span> & Reliable
            </h2>
            <p className="text-base sm:text-lg text-muted-foreground max-w-2xl mx-auto">
              Your data is protected with modern security practices
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {securityFeatures.map((security, index) => (
              <Card 
                key={index} 
                className="p-6 hover-elevate transition-all duration-300"
                data-testid={`security-${index}`}
              >
                <div className="flex flex-col gap-3">
                  <div className="p-3 rounded-lg bg-accent/10 w-fit">
                    <security.icon className="h-7 w-7 text-accent" />
                  </div>
                  <div>
                    <h4 className="text-base font-semibold mb-2">{security.title}</h4>
                    <p className="text-sm text-muted-foreground leading-relaxed">{security.description}</p>
                  </div>
                </div>
              </Card>
            ))}
          </div>
        </div>

        {/* Final CTA Section - Clean & Clear */}
        <div className="rounded-2xl bg-gradient-to-br from-primary/10 via-primary/5 to-accent/10 p-12 md:p-16 text-center border border-primary/20">
          <h2 className="text-2xl sm:text-3xl md:text-4xl font-bold mb-6 bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent">
            Elevate Your Lifestyle
          </h2>
          <p className="text-base sm:text-lg text-muted-foreground mb-10 max-w-2xl mx-auto">
            Join the elite circle of individuals who've mastered the art of sophisticated automation
          </p>
          <Button 
            asChild
            size="lg" 
            className="text-lg px-12 py-6 h-auto rounded-lg bg-primary hover:bg-primary/90 text-primary-foreground shadow-lg shadow-primary/20 transition-all duration-300 relative z-30"
            data-testid="button-sign-in"
          >
            <a href="/api/login">
              <Shield className="mr-2 h-6 w-6" />
              Secure Sign In
            </a>
          </Button>
        </div>
      </div>
    </div>
  );
}
